version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017" # Exponiert MongoDB auf dem Host unter Port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d:ro # Initialisierungsskript laden
    restart: unless-stopped
